package net.sirok.slofisc;

/**
 * Created by martin on 11.2.2016.
 */
public interface EORCallback {
    /**
     * Method is called when EOR number was successfully
     * generated by the FURS server.
     *
     * @param eor EOR number generated by the FURS server
     */
    void success(String eor);

    /**
     * Method is called when the FURS server returns an error.
     *
     * @param errorNumber network response error number
     * @param message FURS fiscalisation error
     */
    void error(int errorNumber, String message);
}
